import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import Image from "next/image";
import Link from "next/link";
import { getServerAuthSession } from "~/server/auth";
import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Ielts prep",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();

  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <div className="border-b border-neutral-200">
            <div className="mx-auto flex h-16 max-w-4xl items-center justify-between py-2">
              <Link href="/">
                <Image src="/logo.svg" alt="logo" width={48} height={36} />
              </Link>
              <div className="flex gap-8">
                <Link className="font-medium text-neutral-400" href="/">
                  What we teach
                </Link>
                <Link className="font-medium text-neutral-400" href="/">
                  Pricing
                </Link>
                <Link className="font-medium text-neutral-400" href="/">
                  Testimonials
                </Link>
              </div>
              <Link
                href={session ? "/api/auth/signout" : "/api/auth/signin"}
                className="rounded-lg bg-black p-1 px-2 text-white"
              >
                {session ? "Sign out" : "Sign in"}
              </Link>
            </div>
          </div>
          <div className="mx-auto max-w-4xl py-3">{children}</div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
